"""init schema

Revision ID: 8ad9f1629a5e
Revises: 
Create Date: 2026-05-01 20:26:26.898928
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8ad9f1629a5e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('markets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.Enum('KALSHI', 'POLYMARKET', name='platform'), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('SPORTS', 'POLITICS', 'FINANCE', name='category'), nullable=False),
    sa.Column('resolution_criteria', sa.Text(), nullable=False),
    sa.Column('close_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('outcome', sa.Enum('YES', 'NO', name='outcome'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_game_stats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('game_date', sa.Date(), nullable=False),
    sa.Column('opponent', sa.Text(), nullable=False),
    sa.Column('home_away', sa.Enum('HOME', 'AWAY', name='home_away'), nullable=False),
    sa.Column('minutes', sa.Float(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('rebounds', sa.Integer(), nullable=False),
    sa.Column('fg_pct', sa.Float(), nullable=False),
    sa.Column('ts_pct', sa.Float(), nullable=False),
    sa.Column('usage_rate', sa.Float(), nullable=False),
    sa.Column('raptor', sa.Float(), nullable=False),
    sa.Column('rest_days', sa.Integer(), nullable=False),
    sa.Column('injury_flag', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_game_stats_game_date'), 'player_game_stats', ['game_date'], unique=False)
    op.create_index(op.f('ix_player_game_stats_player_id'), 'player_game_stats', ['player_id'], unique=False)
    op.create_table('sentiment_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('market_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.Enum('TWITTER', 'REDDIT', 'NEWS', name='sentiment_source'), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('entity', sa.Text(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('sentiment', sa.Enum('POSITIVE', 'NEGATIVE', 'NEUTRAL', name='sentiment_label'), nullable=False),
    sa.Column('credibility_weight', sa.Float(), nullable=False),
    sa.Column('novelty_score', sa.Float(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('market_id', sa.UUID(), nullable=False),
    sa.Column('model_probability', sa.Float(), nullable=False),
    sa.Column('confidence_interval_low', sa.Float(), nullable=False),
    sa.Column('confidence_interval_high', sa.Float(), nullable=False),
    sa.Column('market_price', sa.Float(), nullable=False),
    sa.Column('edge', sa.Float(), nullable=False),
    sa.Column('signal_tier', sa.Enum('STRONG', 'LEAN', 'NONE', 'FADE', name='signal_tier'), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=False),
    sa.Column('sentiment_weight', sa.Float(), nullable=False),
    sa.Column('stats_weight', sa.Float(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('signals')
    op.drop_table('sentiment_events')
    op.drop_index(op.f('ix_player_game_stats_player_id'), table_name='player_game_stats')
    op.drop_index(op.f('ix_player_game_stats_game_date'), table_name='player_game_stats')
    op.drop_table('player_game_stats')
    op.drop_table('markets')
    # ### end Alembic commands ###
