"""add liquidity reasoning relevance

Revision ID: c788370c4966
Revises: e4cc936ffd06
Create Date: 2026-05-02 12:20:54.959821
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c788370c4966'
down_revision: Union[str, None] = 'e4cc936ffd06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('markets', sa.Column('liquidity', sa.Float(), nullable=False, server_default='0'))
    op.add_column('sentiment_events', sa.Column('relevance_score', sa.Float(), nullable=False, server_default='1'))
    op.add_column('sentiment_events', sa.Column('llm_reasoning', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sentiment_events', 'llm_reasoning')
    op.drop_column('sentiment_events', 'relevance_score')
    op.drop_column('markets', 'liquidity')
    # ### end Alembic commands ###
