"""add market external_id

Revision ID: e4cc936ffd06
Revises: 8ad9f1629a5e
Create Date: 2026-05-01 23:11:53.039654
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e4cc936ffd06'
down_revision: Union[str, None] = '8ad9f1629a5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('markets', sa.Column('external_id', sa.Text(), nullable=True))
    op.create_index(op.f('ix_markets_external_id'), 'markets', ['external_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_markets_external_id'), table_name='markets')
    op.drop_column('markets', 'external_id')
    # ### end Alembic commands ###
